name: split_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.29.0
  firebase_auth: ^4.19.2
  cloud_firestore: ^4.17.2
  firebase_analytics: ^10.1.0
  crypto: ^3.0.3
  shared_preferences: ^2.5.3
  intl: ^0.18.1
  fl_chart: ^0.64.0
  csv: ^5.1.1
  path_provider: ^2.1.2
  cached_network_image: ^3.3.1
  provider: ^6.1.1
  image_picker: ^1.0.7
  badges: ^3.1.2
  pdf: ^3.10.4
  printing: ^5.12.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
